### ISSUE TITLE
[r] value filter returns in Python but not R

### ISSUE THREAD

**Issue by mtmorgan** [chanzuckerberg/cellxgene-census#638] opened 2023-07-23 19:12 UTC
## Describe the bug

This Python (modified from the Python '[quick start][]'; I do not have experience with Python) returns a 3371 rows x 7 columns result in a few seconds

[quick start]: https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_quick_start.html#python-quick-start

```{python}
import cellxgene_census

with cellxgene_census.open_soma() as census:
    
    # Reads SOMADataFrame as a slice
    cell_metadata = census["census_data"]["homo_sapiens"].obs.read(
        value_filter = "self_reported_ethnicity == 'African' and tissue == 'lung parenchyma' and cell_type == 'CD4-positive, alpha-beta T cell'",
        column_names = ["assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease"]
    )
    
    # Concatenates results to pyarrow.Table
    cell_metadata = cell_metadata.concat()
    
    # Converts to pandas.DataFrame
    cell_metadata = cell_metadata.to_pandas()
    
    print(cell_metadata)
```

but the equivalent R generates prolonged network activity but does terminate after 10's of minutes

```{r}
library(cellxgene.census)
obs <- open_soma()$get("census_data")$get("homo_sapiens")$get("obs")
result <- obs$read(
    value_filter = paste(
        "self_reported_ethnicity == 'African'",
        "tissue == 'lung parenchyma'",
        "cell_type == 'CD4-positive, alpha-beta T cell'",
        sep = " & "
    ),
    column_names = c(
        "assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease"
    )
)
```

## To Reproduce

I installed tiledb, tiledbsoma, and cellxgene.census from current GitHub checkouts on main / master, with

```{r}
> tiledbsoma::show_package_versions()
tiledbsoma:    0.99.2
tiledb-r:      0.20.1.2
tiledb core:   2.16.0
libtiledbsoma: libtiledb=2.16.0
R:             R version 4.3.1 Patched (2023-07-17 r84704)
OS:            macOS Monterey 12.6.7
> packageVersion("cellxgene.census")
[1] '0.0.0.9000'
```

## Expected behavior

R behaves like Python...

## Environment

```> library(cellxgene.census)
> sessionInfo()
R version 4.3.1 Patched (2023-07-17 r84704)
Platform: aarch64-apple-darwin21.6.0 (64-bit)
Running under: macOS Monterey 12.6.7

Matrix products: default
BLAS:   /Users/ma38727/bin/R-4-3-branch/lib/libRblas.dylib
LAPACK: /Users/ma38727/bin/R-4-3-branch/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] cellxgene.census_0.0.0.9000

loaded via a namespace (and not attached):
 [1] vctrs_0.6.3         httr_1.4.6          cli_3.6.1
 [4] tiledbsoma_0.99.2   rlang_1.1.1         purrr_1.0.1
 [7] assertthat_0.2.1    data.table_1.14.8   jsonlite_1.8.7
[10] glue_1.6.2          bit_4.0.5           triebeard_0.4.1
[13] grid_4.3.1          RcppSpdlog_0.0.14   base64enc_0.1-3
[16] lifecycle_1.0.3     compiler_4.3.1      fs_1.6.3
[19] Rcpp_1.0.11         aws.s3_0.3.21       lattice_0.21-8
[22] digest_0.6.33       R6_2.5.1            tidyselect_1.2.0
[25] curl_5.0.1          magrittr_2.0.3      urltools_1.7.3
[28] Matrix_1.6-0        tools_4.3.1         bit64_4.0.5
[31] aws.signature_0.6.0 spdl_0.0.5          arrow_12.0.1
[34] xml2_1.3.5
```

**Comment by pablo-gar** [comment] 2023-07-24 22:28
Thanks Martin. As you can see we are still in this pre 1.0.0 world. 

This is a known bug in TileDB core 2.16.0, a [PR is up](https://github.com/TileDB-Inc/TileDB/pull/4200) and a patch release will be done later this week.

**Comment by eddelbuettel** [comment] 2023-07-24 22:58
@mtmorgan I can confirm that your query works for me on the ec2 instance where I tested Luc's [PR #4200](https://github.com/TileDB-Inc/TileDB/pull/4200) with him.

**Comment by mtmorgan** [comment] 2023-07-25 15:38
Thank you.

Is the following related? I installed Python using the [instruction for creating a venv][installation] (n.b., python / pip are not automatically aliased to python3 / pip3 in macOS; it would be better to use the unaliased names). When I run the commands for the tutorial [querying expression data][query] I have
```{python}
import cellxgene_census
census = cellxgene_census.open_soma()
adata = cellxgene_census.get_anndata(
    census=census,
    organism="Homo sapiens",
    var_value_filter="feature_id in ['ENSG00000161798', 'ENSG00000188229']",
    obs_value_filter="cell_type == 'B cell' and tissue_general == 'lung' and disease == 'COVID-19'",
    column_names={"obs": ["sex"]},
)
```
and this too seems to get stuck in a download cycle. This is NOT using the patched version PR4200 of tiledb.

[installation]: https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_installation.html
[query]: https://chanzuckerberg.github.io/cellxgene-census/notebooks/api_demo/census_query_extract.html#Querying-expression-data

**Comment by eddelbuettel** [comment] 2023-07-25 15:45
Yes -- I suspect if you turn Core-level logging on (easiest maybe via environment variable `TILEDB_CONFIG_LOGGING_LEVEL` set to `5` aka 'trace') you will see the same few lines repeated over and over which was the symptom we saw from R when @pablo-gar first reported this issue on Friday.  This is addressed by PR 4200 but you would have to build the Python package against it rather than using a PyPi (or alike) download with a pinned released of TileDB that predates the PR.

**Comment by pablo-gar** [comment] 2023-08-08 23:55
The fixes have been incorporated in the R and Python Census packages v1.5.1

**Closed by pablo-gar** 2023-08-08 23:55 UTC
Labels: bug, P0, r api
