### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer') when using cellxgene_census.get_anndata

### ISSUE THREAD

**Issue by xshaaaa** [chanzuckerberg/cellxgene-census#1260] opened 2024-08-11 03:54 UTC
## Describe the bug

When using the requests library to connect to a remote server to fetch data, the connection is reset by the peer (remote server), leading to a ConnectionError. The detailed error message is: Connection aborted., with an accompanying ConnectionResetError(104, 'Connection reset by peer'). This error occurs when attempting to retrieve data from the remote server using the cellxgene_census.get_anndata() function.

## To Reproduce

Run a script on a machine with network access that uses the cellxgene_census.get_anndata() function to fetch data from a remote server.
The code includes a loop that retries the connection in case of a requests.exceptions.ConnectionError.
In certain situations (e.g., network instability or high server load), a connection error occurs, causing the connection to be reset by the peer

## Expected behavior

The expected behavior is that the script should successfully connect to the remote server, retrieve the required data, and process and save it to the local file system.

## Environment

Provide a description of your system and the software versions.

**Comment by xshaaaa** [comment] 2024-08-11 04:00
```
data = cellxgene_census.get_anndata(
                            census=census,
                            organism="Homo sapiens",
                            X_layers=["normalized"],
                            obs_value_filter=f"tissue_general == '{tissue_value}' and disease == '{disease}' and tissue == '{stage}' and is_primary_data == True",
                            var_value_filter=None,
                            column_names={"obs": ["dataset_id", "assay", "cell_type", "development_stage", "disease", 
                                                  "donor_id", "observation_joinid", "self_reported_ethnicity", 
                                                  "sex", "suspension_type", "tissue", "tissue_type", "tissue_general", 
                                                  "raw_sum", "nnz", "raw_mean_nnz", "raw_variance_nnz", 
                                                  "n_measured_vars","is_primary_data"]},
                            obs_embeddings=["scvi","scgpt"],
                        )
```
       When i run this code to download adata, 
 ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
question like this happened, i am a lot of confused and hope to figure out.
Several days ago, when i downloaded, i never met such thing. But maybe three days ago, this question happened and i googled to try to solve it.  Sad to say i have not solve it till now.

**Comment by xshaaaa** [comment] 2024-08-11 05:09
`Traceback (most recent call last):
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/cabins/foundation/foundation/trying/mouse_embryo.py", line 65, in process_and_save_data
    data = cellxgene_census.get_anndata(
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/cellxgene_census/_get_anndata.py", line 160, in get_anndata
    embedding = _get_embedding(census, census_directory, census_version, uri, obs_soma_joinids)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/cellxgene_census/experimental/_embedding.py", line 93, in _get_embedding
    with open_soma(census_version=census_version, context=context) as census:
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/cellxgene_census/_open.py", line 227, in open_soma
    mirrors = _get_census_mirrors()
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/cellxgene_census/_release_directory.py", line 435, in _get_census_mirrors
    response = requests.get(CELL_CENSUS_MIRRORS_DIRECTORY_URL, headers={"User-Agent": _user_agent()})
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/foundation/anaconda3/envs/foundation/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
`

**Comment by ivirshup** [comment] 2024-08-14 17:50
Hi @xshaaaa,

I believe the issue you are running into is due to network issues not totally in our control. We've added caching to the specific requests you were seeing fail which we hope should make this complete more regularly. However, there may not be a ton more we can do at the moment if this doesn't resolve your issue.

Are you seeing successful requests now?

**Comment by xshaaaa** [comment] 2024-08-15 12:24
Hello@ivirshup, 
Thank you very much for your reply and the effort, but unfortunately, I tried just now, but the problem still exists.
Best wishes!

**Comment by ivirshup** [comment] 2024-08-15 15:44
Hmm. Are you able to reproduce the error if you try using a different network? It's also possible this is a firewall from a specific network, which you could ask your admin about.

**Comment by xshaaaa** [comment] 2024-08-18 02:32
Sure! I’ll make sure to discuss this with the admin as soon as possible. Thanks for the suggestion! Thank you very much!

**Comment by ivirshup** [comment] 2024-08-19 18:42
Okay, I'm going to close this for now. Feel free to ping back if you are unable to resolve this!

**Closed by ivirshup** 2024-08-19 18:42 UTC
Labels: bug, network
